### ISSUE TITLE
pkg_resources.UnknownExtra: setuptools-scm 6.2.0 has no such extra feature 'toml'

### ISSUE THREAD

**Issue by marcos-mendez** [erpbrasil/erpbrasil.assinatura#25]
Inside pure debian Buster or Bullseye this error is generated

`pkg_resources.UnknownExtra: setuptools-scm 6.2.0 has no such extra feature 'toml'`

The full error is: 

`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/pip-install-n39yxflj/xmlsec/setup.py", line 440, in <module>
    package_data={'xmlsec': ['py.typed', '*.pyi']},
  File "/tmp/pip-build-env-vjcaqy5g/lib/python3.7/site-packages/setuptools/__init__.py", line 152, in setup
    _install_setup_requires(attrs)
  File "/tmp/pip-build-env-vjcaqy5g/lib/python3.7/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/tmp/pip-build-env-vjcaqy5g/lib/python3.7/site-packages/setuptools/dist.py", line 788, in fetch_build_eggs
    replace_conflicting=True,
  File "/tmp/pip-build-env-vjcaqy5g/lib/python3.7/site-packages/pkg_resources/__init__.py", line 780, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/tmp/pip-build-env-vjcaqy5g/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2743, in requires
    ) from e
pkg_resources.UnknownExtra: setuptools-scm 6.2.0 has no such extra feature 'toml'`

To solve this execute:

$pip3 install --upgrade pip

This will update pip for the execution on python 3.7

Closing issue that was referred by #pr23

**Comment by marcos-mendez** [comment]
@renatonlima não era problema de Venv era isso ai, resolvi

**Comment by marcos-mendez** [comment]
@rvalyi obrigdo pelo apoio
